version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "5000:5000"
    networks:
      - qtasty-network
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_URL=${MONGO_URL}

  order-service:
    build: ./order-service
    ports:
      - "7000:7000"
    networks:
      - qtasty-network
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_URL=${MONGO_URL}

  restaurant-service:
    build: ./restaurant-service
    ports:
      - "3000:3000"
    networks:
      - qtasty-network
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_URL=${MONGO_URL}

  delivery-service:
    build: ./delivery-service
    ports:
      - "6000:6000"
    networks:
      - qtasty-network
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_URL=${MONGO_URL}

  kafka:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"
    networks:
      - qtasty-network

  zookeeper:
    image: wurstmeister/zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - qtasty-network
      
  # admin-service:
  #   build: ./admin-service
  #   ports:
  #     - "8000:8000"
  #   networks:
  #     - qtasty-network

  # auth-service:
  #   build: ./auth-service
  #   ports:
  #     - "9000:9000"
  #   networks:
  #     - qtasty-network

networks:
  qtasty-network:
    driver: bridge
